enum TAB_CONSTANTS {
  PERFORMANCE = '공연',
  EVENT_SHOW = '행사',
  RECRUITMENT = '모집공고',
  APPLY_PARTICIPATION = '참여신청한 행사',
  BOOKMARKED_EVENT = '북마크한 행사',
}

const CURRENT_MAIN_TAB_KEY = 'CURRENT_NEWS_TAB';
const CURRENT_PROFILE_TAB_KEY = 'CURRENT_PROFILE_TAB';

export { TAB_CONSTANTS, CURRENT_MAIN_TAB_KEY, CURRENT_PROFILE_TAB_KEY };
